version: '3'
services:
  api:
    build: .
    command: npm start
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - "mongodb"

  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
