version: '3'
services:
  api:
    image: node:9-alpine
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: npm run start:dev
    ports:
      - 4000:4000
    depends_on:
      - mysql
    container_name: api-dev

  mysql:
    image: mysql:5
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=dborg
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=123321
      - MYSQL_ROOT_PASSWORD=123123
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
