version: '3'
services:
  api:
    build: .
    command: npm run start:dev
    ports:
      - "4000:4000"
    env_file:
      .env.development
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - mysql

  mysql:
    image: mysql:5
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=dborg
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=123321
      - MYSQL_ROOT_PASSWORD=123123
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
