version: '3'
services:
  api-test:
    build: .
    command: npm run start:test
    ports:
      - "4001:4000"
    environment:
      - NODE_ENV=test
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - "mongodb-test"

  mongodb-test:
    image: "mongo"
    ports:
      - "27018:27017"
