version: '3'
services:
  api-dev:
    build: .
    command: npm run dev
    ports:
      - "4001:4000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - "mongodb-dev"

  mongodb-dev:
    image: "mongo"
    ports:
      - "27018:27017"
